### ISSUE TITLE
The `lb` module resources are not checked while `elb` and `alb` are.

### ISSUE THREAD

**Issue by MitchellGerdisch** [pulumi/compliance-policies#46]
### What happened?

The AWS provider has three load balancer modules: elb, alb, and lb.
The alb and lb modules are the same resources with different names (presumably for historical backwards compatibility), but there are no policies checking for resources that are of the `lb` family.

### Example

You can see `alb` and `elb` policies here: https://github.com/pulumi/compliance-policies/tree/main/vendor-aws/aws
And you can see that there is also and `lb` module in the provider here: https://www.pulumi.com/registry/packages/aws/api-docs/lb/

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by aureq** [comment]
Implemented and available in `@pulumi/aws-compliance-policies@0.0.19`
